title: Supreme Court Judgements
remote_theme: opendocsg/opendoc-theme@v2
repository: opendocsg/opendoc-supreme-court-judgments
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: 'https://search.opendoc.sg'
server_DEV: 'https://search-staging.opendoc.sg'
fast_build: true
offline_search_only: false
styling_options:
  primary_brand_color: '#8B4513'
  logo_path: /assets/ic-logo.png
  opendoc_logo_path: /assets/images/logo-full.png
document_order:
  - 2020_SGHC_142
  - 2020_SGHC(I)_16
  - 2020_SGHC(I)_15
  - 2020_SGHC_138
  - 2020_SGHC_139
  - 2020_SGHCF_9
  - 2020_SGCA_64
  - 2020_SGHC_136
  - 2020_SGCA_65
  - 2020_SGHC_137
  - 2020_SGHC_135
  - 2020_SGCA_62
  - 2020_SGCA_63
  - 2020_SGHCR_5
  - 2020_SGCA_61
  - 2020_SGCA_60
  - 2020_SGHC_132
  - 2020_SGHC_133
  - 2020_SGHC_130
  - 2020_SGHC_131
  - 2020_SGHC_129
  - 2020_SGHC_128
  - 2020_SGHC_127
  - 2020_SGHC_123
  - 2020_SGHC_126
  - 2020_SGHC_118
  - 2020_SGHC_125
  - 2020_SGHC_124
  - 2020_SGHC_122
  - 2020_SGHC_120
  - 2020_SGHC_119
  - 2020_SGCA_59
  - 2020_SGCA_57
  - 2020_SGHC_121
  - 2020_SGCA_58
  - 2020_SGCA_56
  - 2020_SGHC_117
  - 2020_SGCA_55
  - 2020_SGHC_115
  - 2020_SGHC_116
  - 2020_SGHC_114
  - 2020_SGHC_112
  - 2020_SGCA_54
  - 2020_SGHCR_4
  - 2020_SGHC_113
  - 2020_SGHC(I)_14
  - 2020_SGHC_110
  - 2020_SGCA_53
  - 2020_SGCA_52
  - 2020_SGHC_111
  - 2020_SGHCR_3
  - 2020_SGHC_107
  - 2020_SGHC_108
  - 2020_SGHC_109
  - 2020_SGHC_105
  - 2020_SGHC_106
  - 2020_SGHC_99
  - 2020_SGHC_104
  - 2020_SGHC_101
  - 2020_SGHC_103
  - 2020_SGCA_51
  - 2020_SGCA_50
  - 2020_SGHC_100
  - 2020_SGHC_97
  - 2020_SGHC_102
  - 2020_SGCA_49
  - 2020_SGHC_98
  - 2020_SGCA_48
  - 2020_SGCA_46
  - 2020_SGHC(I)_11
  - 2020_SGCA_47
  - 2020_SGHC_96
  - 2020_SGHC_95
  - 2020_SGHC(I)_12
  - 2020_SGHC_70
  - 2020_SGHC_94
  - 2020_SGHC_92
  - 2020_SGHC_90
  - 2020_SGCA_45
  - 2020_SGHC_91
  - 2020_SGHC_93
  - 2020_SGCA_41
  - 2020_SGHC_87
  - 2020_SGCA_44
  - 2020_SGHC(I)_8
  - 2020_SGHC_89
  - 2020_SGHC_88
  - 2020_SGHC_86
  - 2020_SGHC_83
  - 2020_SGCA_43
  - 2020_SGHC(I)_10
  - 2020_SGHC_85
  - 2020_SGHC_79
  - 2020_SGHC_84
  - 2020_SGHC_80
  - 2020_SGCA_40
  - 2020_SGCA_42
  - 2020_SGHC_78
  - 2020_SGHC_81
  - 2020_SGHC_82
  - 2020_SGCA_39
  - 2020_SGCA_38
  - 2020_SGHC_76
  - 2020_SGHC(I)_9
  - 2020_SGCA_37
  - 2020_SGHC_75
  - 2020_SGHC_77
  - 2020_SGHC_73
  - 2020_SGHC_74
  - 2020_SGCA_36
  - 2020_SGHC_72
  - 2020_SGCA_35
  - 2020_SGHC_67
  - 2020_SGHC_69
  - 2020_SGCA_33
  - 2020_SGCA_34
  - 2020_SGCA_31
  - 2020_SGHC_71
  - 2020_SGCA_32
  - 2020_SGHC_65
  - 2020_SGCA_29
  - 2020_SGCA_28
  - 2020_SGHCR_2
  - 2020_SGHC_66
  - 2020_SGHC_64
  - 2020_SGHC_50
  - 2020_SGCA_26
  - 2020_SGCA_27
  - 2020_SGCA_25
  - 2020_SGHC_63
  - 2020_SGCA_24
  - 2020_SGHC_62
  - 2020_SGCA_23
  - 2020_SGHC_61
  - 2020_SGCA_19
  - 2020_SGHC_60
  - 2020_SGCA_22
  - 2020_SGCA_17
  - 2020_SGHC_58
  - 2020_SGHCF_8
  - 2020_SGCA_21
  - 2020_SGCA_20
  - 2020_SGHC_54
  - 2020_SGHC_52
  - 2020_SGCA_18
  - 2020_SGHC_59
  - 2020_SGHC_56
  - 2020_SGHC_57
  - 2020_SGHC_55
  - 2020_SGHCF_7
  - 2020_SGHC_53
  - 2020_SGHC_47
  - 2020_SGCA_16
  - 2020_SGHC_48
  - 2020_SGHCF_6
  - 2020_SGHC_51
  - 2020_SGCA_14
  - 2020_SGHC_49
  - 2020_SGHC_46
  - 2020_SGHCF_5
  - 2020_SGCA_15
  - 2020_SGHC_44
  - 2020_SGCA_13
  - 2020_SGHC_45
  - 2020_SGHC_42
  - 2020_SGHC(I)_6
  - 2020_SGHC(I)_5
  - 2020_SGHC_43
  - 2020_SGHC(I)_7
  - 2020_SGHC_40
  - 2020_SGHC_41
  - 2020_SGCA_12
  - 2020_SGCA_11
  - 2020_SGCA_9
  - 2020_SGCA_10
  - 2020_SGCA_8
  - 2020_SGCA(I)_2
  - 2020_SGHC_39
  - 2020_SGHC_11
  - 2020_SGHC_38
  - 2020_SGHC(I)_03
  - 2020_SGHC_37
  - 2020_SGHC_34
  - 2020_SGHC_36
  - 2020_SGHC_35
  - 2020_SGHC_32
  - 2020_SGHCF_4
  - 2020_SGHC_33
  - 2020_SGHC_30
  - 2020_SGHC_31
  - 2020_SGHCF_3
  - 2020_SGCA(I)_1
  - 2020_SGHC_29
  - 2020_SGHC_28
  - 2020_SGCA_7
  - 2020_SGCA_6
  - 2020_SGCA_5
  - 2020_SGHC_27
  - 2020_SGHC_26
  - 2020_SGCA_4
  - 2020_SGHC(I)_2
  - 2020_SGHC_25
  - 2020_SGHC_12
  - 2020_SGHC_21
  - 2020_SGHC_24
  - 2020_SGHC_23
  - 2020_SGHC_22
  - 2020_SGHC_20
  - 2020_SGCA_3
  - 2020_SGHC_17
  - 2020_SGHC_19
  - 2020_SGHC_18
  - 2020_SGHCR_1
  - 2020_SGHC_16
  - 2020_SGHC_15
  - 2020_SGCA_2
  - 2020_SGHC_14
  - 2020_SGHC_13
  - 2020_SGHC_10
  - 2020_SGCA_1
  - 2020_SGHC_9
  - 2020_SGHC_8
  - 2020_SGHCF_2
  - 2020_SGHCF_1
  - 2020_SGHC_7
  - 2020_SGHC(I)_1
  - 2020_SGHC_6
  - 2020_SGHC_5
  - 2020_SGHC_2
  - 2020_SGHC_3
  - 2020_SGHC_4
  - 2019_SGHC_293
  - 2020_SGHC_1
  - 2019_SGHC_292
  - 2019_SGCA_84
  - 2019_SGHC_287
  - 2019_SGHC_291
  - 2019_SGHC_290
  - 2019_SGCA_82
  - 2019_SGCA_83
  - 2019_SGHC_282
  - 2019_SGHCF_26
  - 2019_SGHCF_28
  - 2019_SGHCF_27
  - 2019_SGHCR_12
  - 2019_SGHCF_25
  - 2019_SGHC_277
  - 2019_SGHC_289
  - 2019_SGHC_288
  - 2019_SGHC_286
  - 2019_SGHCF_24
  - 2019_SGHC_283
  - 2019_SGHC_285
  - 2019_SGHC_284
  - 2019_SGHC_281
  - 2019_SGCA_80
  - 2019_SGHC_280
  - 2019_SGCA_79
  - 2019_SGHC_279
  - 2019_SGCA_81
  - 2019_SGHC_278
  - 2019_SGHC_274
  - 2019_SGHC_276
  - 2019_SGCA_78
  - 2019_SGCA_75
  - 2019_SGCA_77
  - 2019_SGHC_275
  - 2019_SGCA_76
  - 2019_SGCA_74
  - 2019_SGHC_272
  - 2019_SGCA_73
  - 2019_SGHC_273
  - 2019_SGCA_65
  - 2019_SGCA_71
  - 2019_SGHC_269
  - 2019_SGHC_270
  - 2019_SGCA_72
  - 2019_SGCA_70
  - 2019_SGHC_260
  - 2019_SGHC_271
  - 2019_SGCA_69
  - 2019_SGHC_254
  - 2019_SGHC_268
  - 2019_SGCA_66
  - 2019_SGCA_67
  - 2019_SGCA_68
  - 2019_SGCA_64
  - 2019_SGHC_266
  - 2019_SGHC_265
  - 2019_SGHC_267
  - 2019_SGHCF_23
  - 2019_SGCA_63
  - 2019_SGCA_62
  - 2019_SGCA_61
  - 2019_SGCA_60
  - 2019_SGHC_261
  - 2019_SGHC_263
  - 2019_SGHC_264
  - 2019_SGHC_259
  - 2019_SGHC_258
  - 2019_SGHC_262
  - 2019_SGHC_257
  - 2019_SGHC_256
  - 2019_SGCA_59
  - 2019_SGHC_255
  - 2019_SGHC_251
  - 2019_SGCA_57
  - 2019_SGHC_253
  - 2019_SGHC_252
  - 2019_SGCA_56
  - 2019_SGHC_250
  - 2019_SGHC_248
  - 2019_SGHC_249
  - 2019_SGHC_247
  - 2019_SGHCF_22
  - 2019_SGHC_246
  - 2019_SGHC_245
  - 2019_SGHC_242
  - 2019_SGCA_55
  - 2019_SGHC(I)_15
  - 2019_SGHC_244
  - 2019_SGHC_243
  - 2019_SGHC_241
  - 2019_SGCA_54
  - 2019_SGHC_240
  - 2019_SGHC_239
  - 2019_SGHC_238
  - 2019_SGHC_237
  - 2019_SGHC_236
  - 2019_SGHC_227
  - 2019_SGCA_50
  - 2019_SGHC_233
  - 2019_SGHC_235
  - 2019_SGHC_231
  - 2019_SGHC_234
  - 2019_SGCA_53
  - 2019_SGHC_230
  - 2019_SGHC_232
  - 2019_SGCA_52
  - 2019_SGCA_51
  - 2019_SGHC_228
  - 2019_SGHC_229
  - 2019_SGHC_222
  - 2019_SGHC_226
  - 2019_SGHC_224
  - 2019_SGHC_225
  - 2019_SGHC_223
  - 2019_SGHC_219
  - 2019_SGHC_216
  - 2019_SGHC_220
  - 2019_SGHC_217
  - 2019_SGHC_218
  - 2019_SGHC_221
  - 2019_SGHC_214
  - 2019_SGHC_215
  - 2019_SGHC_213
  - 2019_SGHC_212
  - 2019_SGCA_48
  - 2019_SGHCF_21
  - 2019_SGHC(I)_14
  - 2019_SGHC(I)_12
  - 2019_SGHC_211
  - 2019_SGCA_49
  - 2019_SGHC_209
  - 2019_SGHC(I)_13
  - 2019_SGHC_208
  - 2019_SGHC_210
  - 2019_SGHC_206
  - 2019_SGHC_207
  - 2019_SGHC_205
  - 2019_SGHC_141
  - 2019_SGHC_204
  - 2019_SGHC_201
  - 2019_SGHC_198
  - 2019_SGHC_196
  - 2019_SGHC_203
  - 2019_SGHCF_20
  - 2019_SGHC_200
  - 2019_SGHC_199
  - 2019_SGHCR_11
  - 2019_SGHC_194
  - 2019_SGHC_195
  - 2019_SGHC_197
  - 2019_SGHC_193
  - 2019_SGHCF_19
  - 2019_SGHC_192
  - 2019_SGHC_190
  - 2019_SGHC_191
  - 2019_SGHC_189
  - 2019_SGHC_186
  - 2019_SGHC_188
  - 2019_SGHC_187
  - 2019_SGHC_182
  - 2019_SGHC_184
  - 2019_SGHC_185
  - 2019_SGHC_183
  - 2019_SGCA_47
  - 2019_SGHC_181
  - 2019_SGCA_46
  - 2019_SGHC_179
  - 2019_SGCA_45
  - 2019_SGHC(I)_11
  - 2019_SGHC_180
  - 2019_SGCA_43
  - 2019_SGHCF_18
  - 2019_SGHC_178
  - 2019_SGHC_177
  - 2019_SGCA_44
  - 2019_SGHCF_17
  - 2019_SGHC_175
  - 2019_SGHC_173
  - 2019_SGCA_42
  - 2019_SGHC_174
  - 2019_SGHC_172
  - 2019_SGHC_169
  - 2019_SGHC_170
  - 2019_SGCA_41
  - 2019_SGHC_171
  - 2019_SGHC_168
  - 2019_SGHC_164
  - 2019_SGHC_167
  - 2019_SGHC_166
  - 2019_SGHCF_16
  - 2019_SGCA_40
  - 2019_SGHC_163
  - 2019_SGHC_165
  - 2019_SGHC_161
  - 2019_SGHC_162
  - 2019_SGHC_158
  - 2019_SGHC_155
  - 2019_SGHC_160
  - 2019_SGHC_159
  - 2019_SGHC_156
  - 2019_SGHC_157
  - 2019_SGHC_142
  - 2019_SGHC_153
  - 2019_SGHCR_10
  - 2019_SGHC_152
  - 2019_SGHC_154
  - 2019_SGHC(I)_10
  - 2019_SGHCF_15
  - 2019_SGHC_148
  - 2019_SGHC_140
  - 2019_SGHCR_9
  - 2019_SGHC_151
  - 2019_SGHC_150
  - 2019_SGHC_149
  - 2019_SGHC_146
  - 2019_SGHC_147
  - 2019_SGHC(I)_9
  - 2019_SGHCF_14
  - 2019_SGHC_145
  - 2019_SGHC_139
  - 2019_SGHC_144
  - 2019_SGHC_143
  - 2019_SGHC(I)_8
  - 2019_SGHCF_13
  - 2019_SGHC_138
  - 2019_SGHC_134
  - 2019_SGCA_39
  - 2019_SGHCF_12
  - 2019_SGHC_137
  - 2019_SGCA(I)_1
  - 2019_SGHC_133
  - 2019_SGHC_136
  - 2019_SGHC_135
  - 2019_SGCA_38
  - 2019_SGCA_37
  - 2019_SGHC_132
  - 2019_SGHC(I)_7
  - 2019_SGHC_131
  - 2019_SGHC_130
  - 2019_SGHC_129
  - 2019_SGCA_35
  - 2019_SGHC_123
  - 2019_SGCA_36
  - 2019_SGHC_128
  - 2019_SGHC_127
  - 2019_SGHC_124
  - 2019_SGHC_126
  - 2019_SGHC_125
  - 2019_SGHC(I)_6
  - 2019_SGHC_121
  - 2019_SGCA_33
  - 2019_SGCA_34
  - 2019_SGHC_122
  - 2019_SGHC_120
  - 2019_SGHC_119
  - 2019_SGHC_112
  - 2019_SGHCR_8
  - 2019_SGHC_118
  - 2019_SGHCR_7
  - 2019_SGHCF_10
  - 2019_SGCA_32
  - 2019_SGHC_115
  - 2019_SGHC(I)_5
  - 2019_SGCA_28
  - 2019_SGHC_116
  - 2019_SGHC_117
  - 2019_SGHC_114
  - 2019_SGCA_29
  - 2019_SGCA_31
  - 2019_SGCA_30
  - 2019_SGHC_113
  - 2019_SGHC_109
  - 2019_SGHC_110
  - 2019_SGHC_108
  - 2019_SGHC_111
  - 2019_SGHC_107
  - 2019_SGHCF_9
  - 2019_SGHC_106
  - 2019_SGCA_27
  - 2019_SGHC_103
  - 2019_SGHC_104
  - 2019_SGHC_101
  - 2019_SGHCF_8
  - 2019_SGHC_102
  - 2019_SGHC_105
  - 2019_SGHC_96
  - 2019_SGHC_97
  - 2019_SGHC_99
  - 2019_SGHC_98
  - 2019_SGHC_100
  - 2019_SGHC_95
  - 2019_SGHC(I)_4
  - 2019_SGHC_91
  - 2019_SGHC_93
  - 2019_SGHC_94
  - 2019_SGCA_23
  - 2019_SGCA_22
  - 2019_SGCA_26
  - 2019_SGCA_25
  - 2019_SGCA_24
  - 2019_SGHC_92
  - 2019_SGCA_21
  - 2019_SGHC_70
  - 2019_SGHC_88
  - 2019_SGHC_90
  - 2019_SGHC_68
  - 2019_SGHC_89
  - 2019_SGCA_20
  - 2019_SGHC_85
  - 2019_SGHC_87
  - 2019_SGHC_86
  - 2019_SGHC_84
  - 2019_SGHCF_7
  - 2019_SGHC_81
  - 2019_SGCA_19
  - 2019_SGHC_82
  - 2019_SGHC_83
  - 2019_SGHC_80
  - 2019_SGCA_18
  - 2019_SGHC_77
  - 2019_SGHC_67
  - 2019_SGHC_75
  - 2019_SGHC_78
  - 2019_SGHC_79
  - 2019_SGHC_74
  - 2019_SGHC_76
  - 2019_SGHC_61
  - 2019_SGHC_52
  - 2019_SGCA_17
  - 2019_SGHC_72
  - 2019_SGHC_73
  - 2019_SGHC_69
  - 2019_SGHC_71
  - 2019_SGHC(I)_3
  - 2019_SGHC_64
  - 2019_SGHC_65
  - 2019_SGHC_66
  - 2019_SGHC_49
  - 2019_SGHC_63
  - 2019_SGHC(I)_2
  - 2019_SGHC_62
  - 2019_SGHC_59
  - 2019_SGHC_60
  - 2019_SGHCF_6
  - 2019_SGCA_16
  - 2019_SGHC_57
  - 2019_SGHC_58
  - 2019_SGHC_50
  - 2019_SGHC_55
  - 2019_SGHC_54
  - 2019_SGHCR_6
  - 2019_SGHC_56
  - 2019_SGHC_53
  - 2019_SGHC_51
  - 2019_SGHC_48
  - 2019_SGHC_45
  - 2019_SGHC_46
  - 2019_SGHC_44
  - 2019_SGHC_47
  - 2019_SGHC_43
  - 2019_SGHC_42
  - 2019_SGCA_15
  - 2019_SGHCR_4
  - 2019_SGCA_14
  - 2019_SGCA_13
  - 2019_SGHC_41
  - 2019_SGHC_40
  - 2019_SGCA_12
  - 2019_SGHC_39
  - 2019_SGHCR_5
  - 2019_SGHC_36
  - 2019_SGHC_38
  - 2019_SGCA_11
  - 2019_SGHC_34
  - 2019_SGHC_37
  - 2019_SGHC_30
  - 2019_SGHC_35
  - 2019_SGHC_31
  - 2019_SGHC_32
  - 2019_SGHC_27
  - 2019_SGHC_33
  - 2019_SGCA_10
  - 2019_SGHC_29
  - 2019_SGHC_28
  - 2019_SGHC_24
  - 2019_SGHC_26
  - 2019_SGHC_23
  - 2019_SGCA_9
  - 2019_SGHC_25
  - 2019_SGHC_21
  - 2019_SGHC_20
  - 2019_SGHC_22
  - 2019_SGHC_19
  - 2019_SGHC_14
  - 2019_SGHCF_5
  - 2019_SGHC_18
  - 2019_SGHC_16
  - 2019_SGHC_17
  - 2019_SGHCR_3
  - 2019_SGCA_8
  - 2019_SGHC_15
  - 2019_SGHC_13
  - 2019_SGHCF_4
  - 2019_SGCA_7
  - 2019_SGHCF_3
  - 2019_SGHC_6
  - 2019_SGHC_9
  - 2019_SGHC_12
  - 2019_SGHC_8
  - 2019_SGHC_4
  - 2019_SGHC_10
  - 2019_SGHC_11
  - 2019_SGCA_6
  - 2019_SGHC_7
  - 2019_SGHCR_2
  - 2019_SGCA_5
  - 2019_SGHC_5
  - 2019_SGHCF_2
  - 2019_SGCA_3
  - 2019_SGHCF_1
  - 2019_SGCA_4
  - 2019_SGHC(I)_1
  - 2019_SGCA_2
  - 2019_SGCA_1
  - 2019_SGHC_1
  - 2018_SGHC_280
  - 2018_SGHC_277
  - 2018_SGHC_279
  - 2019_SGHC_3
  - 2018_SGHCF_22
  - 2018_SGHC_276
  - 2019_SGHCR_1
  - 2019_SGHC_2
  - 2018_SGHC_278
  - 2018_SGHCF_21
  - 2018_SGHC_272
  - 2018_SGHC_269
  - 2018_SGHC_274
  - 2018_SGHC_275
  - 2018_SGHC_267
  - 2018_SGHCF_18
  - 2018_SGHC_273
  - 2018_SGHCF_20
  - 2018_SGHC_271
  - 2018_SGHC_270
  - 2018_SGCA_87
  - 2018_SGHCF_19
  - 2018_SGHC_264
  - 2018_SGHC_268
