title: Supreme Court Judgements
remote_theme: opendocsg/opendoc-theme@single-page
repository: opendocsg/opendoc-supreme-court-judgments
plugins:
  - jekyll-include-cache
baseurl: ''
server_PROD: 'https://search.opendoc.sg'
server_DEV: 'https://search-staging.opendoc.sg'
fast_build: true
offline: false

styling_options:
  primary_brand_color: '#8B4513'
  logo_path: /assets/ic-logo.png
  opendoc_logo_path: /assets/images/logo-full.png

